# Generated by Django 4.2.3 on 2023-07-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='prince',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
